### B.Thanushan
### Spetember 2021

In [1]:
#impoting pandas package
import pandas as pd

In [2]:
#read the male text file and save it in a pandas dataframe
df_males = pd.read_csv('male.txt', delimiter =' ', header = None, names= ['names'])

In [3]:
df_males.head(10)

names
0      චමුදිත
1      එඩ්වඩ්
2       ජයදේශ
3  ක්‍රිෂාන්ත
4        චතුර
5     ධර්මදාස
6       චන්දන
7    මොහිදීන්
8      මධුසංඛ
9        කමල්

In [4]:
#take the size of the male names
df_males.size

246

In [5]:
#create a list of 1's as the size of the male names 
male_labels = [1]*df_males.size # crea
male_labels

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [6]:
#create a column for the label and pass the list of 1's to it, here we label the males names as 1
df_males['label'] = male_labels

In [7]:
df_males

names  label
0        චමුදිත      1
1        එඩ්වඩ්      1
2         ජයදේශ      1
3    ක්‍රිෂාන්ත      1
4          චතුර      1
..          ...    ...
241    ස්ටැන්ලි      1
242      කීර්ති      1
243      විශ්වා      1
244       ආත්මා      1
245      ගාමිණී      1

[246 rows x 2 columns]

In [8]:
#read the female text file and save it in a pandas dataframe
df_females = pd.read_csv('female.txt',delimiter = " ", names=['names'])
df_females

names
0       පතිනි
1       ගයංගා
2      දිනිඳි
3      ජිත්මි
4    දෙව්මිණි
..        ...
206     හර්ෂි
207    මැණිකේ
208  මරියසෙල්
209    මානෙල්
210    කුසුම්

[211 rows x 1 columns]

In [9]:
#create a list of 0's as the size of the female names 
female_labels = [0]*df_females.size

In [10]:
#create a column for the label and pass the list of 0's to it, here we label the females names as 0
df_females['label']=female_labels

In [11]:
df_females

names  label
0       පතිනි      0
1       ගයංගා      0
2      දිනිඳි      0
3      ජිත්මි      0
4    දෙව්මිණි      0
..        ...    ...
206     හර්ෂි      0
207    මැණිකේ      0
208  මරියසෙල්      0
209    මානෙල්      0
210    කුසුම්      0

[211 rows x 2 columns]

In [12]:
#append both male and female datafam together
Data = df_males.append(df_females)
Data

names  label
0        චමුදිත      1
1        එඩ්වඩ්      1
2         ජයදේශ      1
3    ක්‍රිෂාන්ත      1
4          චතුර      1
..          ...    ...
206       හර්ෂි      0
207      මැණිකේ      0
208    මරියසෙල්      0
209      මානෙල්      0
210      කුසුම්      0

[457 rows x 2 columns]

In [13]:
from sklearn.utils import shuffle

# shuffle the dataframe
data = shuffle(Data, random_state=0)
data = data.reset_index(drop=True)#to reset the index of the new dataframe
data.head(20)

names  label
0         අතුල      1
1        ශර්ලි      1
2        අරුණි      0
3        ලහිරු      1
4     ප්‍රභාත්      1
5          ලතා      0
6       විනාලි      0
7        ලයනල්      1
8        පසිඳු      1
9         සනත්      1
10        චාමර      1
11        අනුර      1
12  දිනේෂ්ෂාන්      1
13       ධනපාල      1
14   සුනේත්‍රා      0
15     නිර්මලා      0
16        සමන්      1
17      කුසුම්      0
18        රමෝල      1
19      වෙරංගි      0

In [14]:
data.dtypes

names    object
label     int64
dtype: object

In [15]:
data.head()

names  label
0      අතුල      1
1     ශර්ලි      1
2     අරුණි      0
3     ලහිරු      1
4  ප්‍රභාත්      1

In [16]:
#get all the names of to the names feature
names_features  = data['names']
names_features

0          අතුල
1         ශර්ලි
2         අරුණි
3         ලහිරු
4      ප්‍රභාත්
         ...   
452       උදාරා
453       ලලිත්
454       නාගිත
455       අජන්ත
456      දුලාන්
Name: names, Length: 457, dtype: object

In [17]:
#import the count vectorizer 
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
vectorizer = CountVectorizer(encoding='utf-8',strip_accents='unicode') #define the vectorizer
X = vectorizer.fit_transform(names_features) #transform the features in numerical form

In [19]:
vectorizer.get_feature_names()

['අකල',
 'අචල',
 'අජ',
 'අජනත',
 'අත',
 'අද',
 'අන',
 'අම',
 'අමර',
 'අමරස',
 'අයනත',
 'අර',
 'අරව',
 'අවනත',
 'අස',
 'ආතම',
 'ආනනද',
 'ආමනත',
 'ආස',
 'ඇනටන',
 'ඇනතන',
 'ඇනසල',
 'ඉන',
 'ඉනද',
 'ඉඳ',
 'ඉම',
 'ඉමලක',
 'ඉර',
 'ඉෂ',
 'ඉස',
 'උද',
 'උදය',
 'උප',
 'උපම',
 'උමය',
 'උර',
 'උෂ',
 'එඩවඩ',
 'එරනද',
 'ඔලබන',
 'ඕෂ',
 'කටර',
 'කමණ',
 'කමන',
 'කමල',
 'කල',
 'කලප',
 'කලපන',
 'කලහ',
 'කව',
 'කෂ',
 'කස',
 'කසන',
 'කසව',
 'කළ',
 'කළණ',
 'ගන',
 'ගය',
 'ගයත',
 'ගයනත',
 'ගර',
 'ගල',
 'චත',
 'චන',
 'චනද',
 'චනදන',
 'චම',
 'චමත',
 'චමප',
 'චර',
 'ජගත',
 'ජත',
 'ජන',
 'ජය',
 'ජයද',
 'ජයන',
 'ජයලත',
 'ජල',
 'ජස',
 'ණද',
 'තක',
 'තන',
 'තම',
 'තර',
 'තස',
 'දත',
 'දද',
 'දධ',
 'දම',
 'දමයනත',
 'දමසත',
 'දය',
 'දරශන',
 'ධන',
 'ධනප',
 'ධමම',
 'ධර',
 'ධරමද',
 'ධරමප',
 'ධරමස',
 'ධව',
 'නක',
 'නත',
 'නතක',
 'නද',
 'නදන',
 'නනද',
 'නනදන',
 'නම',
 'නර',
 'නල',
 'නව',
 'නස',
 'පත',
 'පරල',
 'පරස',
 'පව',
 'පස',
 'බණඩ',
 'බනද',
 'බනධ',
 'මද',
 'මධ',
 'මන',
 'මම',
 'මර',
 'මරව',
 'මරස',
 'මල',
 'මලක',
 'ම

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
Y = data['label']

In [22]:
#split the dataset into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.3,random_state=20)

In [23]:
#classifiers
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import SGDClassifier

In [24]:
from sklearn.metrics import confusion_matrix

In [25]:
from sklearn import metrics
import numpy as np

# Define function to calculate the 4 common mertics
def get_metrics(true_labels, predicted_labels):
    
    print('Accuracy:', np.round(
                        metrics.accuracy_score(true_labels, 
                                               predicted_labels),
                        2))
    print('Precision:', np.round(
                        metrics.precision_score(true_labels, 
                                               predicted_labels,
                                               average='weighted'),
                        2))
    print('Recall:', np.round(
                        metrics.recall_score(true_labels, 
                                               predicted_labels,
                                               average='weighted'),
                        2))
    print('F1 Score:', np.round(
                        metrics.f1_score(true_labels, 
                                               predicted_labels,
                                               average='weighted'),
                        2))

In [26]:
#define the classifiers
mnb = MultinomialNB()
svm = SGDClassifier(loss='hinge', max_iter=100)

In [27]:
#fit the multinomial naive bayes classifer
mnb.fit(X_train,Y_train)

MultinomialNB()

In [28]:
#predict the test data using naive bayes classifer
mnb_predictions = mnb.predict(X_test)

In [29]:
#call the get metrics function to get the evaluation metrics
get_metrics(true_labels=Y_test,predicted_labels=mnb_predictions)

Accuracy: 0.55
Precision: 0.55
Recall: 0.55
F1 Score: 0.48


In [30]:
#get the confusion matrix
confusion_matrix(Y_test,mnb_predictions)

array([[11, 53],
       [ 9, 65]], dtype=int64)

In [31]:
#train the svm classifer using training data
svm.fit(X_train,Y_train)

SGDClassifier(max_iter=100)

In [32]:
#predict the test data using Svm
svm_predictions = svm.predict(X_test)

In [33]:
#call the get matrix function to get the evaluation matrix
get_metrics(true_labels=Y_test,predicted_labels=svm_predictions)

Accuracy: 0.48
Precision: 0.5
Recall: 0.48
F1 Score: 0.43


In [34]:
#get the confusion matrix of svm
confusion_matrix(Y_test,svm_predictions)

array([[50, 14],
       [58, 16]], dtype=int64)

We can see that the accuracy, precision, recall and f1 score are not good for both naive bayes and SVM classifier. Therefore let's try consider last two letters as they best indicators for names in sinhala.

In [35]:
#import the re 
import re

In [36]:
#get the list of all the letters in the names using pattern, this is because if we try to get the last two letters directly
#it shows the part of a chracter and that is misleading so we use pattern to get all the letters and then combine them to get the last two letters
names_list = [re.findall(r'\w\W?',name) for name in data['names']]
names_list

[['අ', 'තු', 'ල'],
 ['ශ', 'ර්', 'ලි'],
 ['අ', 'රු', 'ණි'],
 ['ල', 'හි', 'රු'],
 ['ප්', 'ර', 'භා', 'ත්'],
 ['ල', 'තා'],
 ['වි', 'නා', 'ලි'],
 ['ල', 'ය', 'න', 'ල්'],
 ['ප', 'සි', 'ඳු'],
 ['ස', 'න', 'ත්'],
 ['චා', 'ම', 'ර'],
 ['අ', 'නු', 'ර'],
 ['දි', 'නේ', 'ෂ්', 'ෂා', 'න්'],
 ['ධ', 'න', 'පා', 'ල'],
 ['සු', 'නේ', 'ත්', 'රා'],
 ['නි', 'ර්', 'ම', 'ලා'],
 ['ස', 'ම', 'න්'],
 ['කු', 'සු', 'ම්'],
 ['ර', 'මෝ', 'ල'],
 ['වෙ', 'රං', 'ගි'],
 ['එ', 'ඩ්', 'ව', 'ඩ්'],
 ['ලු', 'ලි', 'ත'],
 ['ර', 'ෂි', 'න්', 'ත', 'ක'],
 ['ක', 'ල්', 'හා', 'රි'],
 ['ස', 'ලී', 'ම්'],
 ['ටෙ', 'ෂා', 'න්', 'ත'],
 ['මි', 'හි', 'රා', 'නි'],
 ['අ', 'ය', 'න්', 'ති', 'කා'],
 ['ම', 'හි', 'ම'],
 ['නි', 'ලූ', 'කා'],
 ['මා', 'ලි', 'ක'],
 ['ක', 'ළ', 'ණ'],
 ['ච', 'න්', 'ද්', 'ර', 'ලේ', 'ඛා'],
 ['ක', 'ම', 'නි', 'කා'],
 ['ජි', 'ත්', 'මි'],
 ['මා', 'ල', 'තී'],
 ['ව', 'ස', 'න්', 'තා'],
 ['ජි', 'නා', 'ගි'],
 ['රු', 'ක්', 'ම', 'ණී'],
 ['නෙ', 'ල්', 'ස', 'න්'],
 ['ච', 'තු', 'රා', 'දි'],
 ['ෆ්', 'රෙ', 'ඩී'],
 ['වි', 'රා', 'ජ්'],
 ['නි', 'ශා', 'න්

#test to take two letters
for i in names_list:
    k = ''.join(i[-2:])
    print(k)

In [37]:
#define a function to get the last two letters into a list of dictionary 
def lastletters(name):
    list = []
    for i in names_list:
        L_letter = ''.join(i[-1:])
        L2_letter = ''.join(i[-2:])
        list.append({'last_letter' : L_letter,'last2_letters' : L2_letter})
    return list    

In [38]:
#now we can get the list of dictionary of last letter and last two letters
data_X = lastletters(names_list)
data_X

[{'last_letter': 'ල', 'last2_letters': 'තුල'},
 {'last_letter': 'ලි', 'last2_letters': 'ර්ලි'},
 {'last_letter': 'ණි', 'last2_letters': 'රුණි'},
 {'last_letter': 'රු', 'last2_letters': 'හිරු'},
 {'last_letter': 'ත්', 'last2_letters': 'භාත්'},
 {'last_letter': 'තා', 'last2_letters': 'ලතා'},
 {'last_letter': 'ලි', 'last2_letters': 'නාලි'},
 {'last_letter': 'ල්', 'last2_letters': 'නල්'},
 {'last_letter': 'ඳු', 'last2_letters': 'සිඳු'},
 {'last_letter': 'ත්', 'last2_letters': 'නත්'},
 {'last_letter': 'ර', 'last2_letters': 'මර'},
 {'last_letter': 'ර', 'last2_letters': 'නුර'},
 {'last_letter': 'න්', 'last2_letters': 'ෂාන්'},
 {'last_letter': 'ල', 'last2_letters': 'පාල'},
 {'last_letter': 'රා', 'last2_letters': 'ත්රා'},
 {'last_letter': 'ලා', 'last2_letters': 'මලා'},
 {'last_letter': 'න්', 'last2_letters': 'මන්'},
 {'last_letter': 'ම්', 'last2_letters': 'සුම්'},
 {'last_letter': 'ල', 'last2_letters': 'මෝල'},
 {'last_letter': 'ගි', 'last2_letters': 'රංගි'},
 {'last_letter': 'ඩ්', 'last2_letter

In [39]:
#take the labels of the names
data_Y = data['label']

In [40]:
from sklearn.feature_extraction import DictVectorizer

In [41]:
#trainAnd test split
XD_train,XD_test,YD_train,YD_test = train_test_split(data_X,data_Y,test_size=0.3,random_state=20)

In [42]:
#display the first 10 training features
XD_train[:10]

[{'last_letter': 'ලා', 'last2_letters': 'නීලා'},
 {'last_letter': 'න්', 'last2_letters': 'ෂන්'},
 {'last_letter': 'ල්', 'last2_letters': 'සෙල්'},
 {'last_letter': 'මි', 'last2_letters': 'ශ්මි'},
 {'last_letter': 'ලා', 'last2_letters': 'මිලා'},
 {'last_letter': 'න්', 'last2_letters': 'ෂාන්'},
 {'last_letter': 'කා', 'last2_letters': 'තිකා'},
 {'last_letter': 'දි', 'last2_letters': 'න්දි'},
 {'last_letter': 'රා', 'last2_letters': 'මරා'},
 {'last_letter': 'රි', 'last2_letters': 'සිරි'}]

In [43]:
#display the first ten training labels 
YD_train[:10]

295    0
367    1
284    0
254    0
109    0
345    1
53     0
323    0
388    0
83     1
Name: label, dtype: int64

In [44]:
Dict_vectorizer = DictVectorizer()# define the dict vectorizer to transform the dictionary to sparce matrix of features
Dict_vectorizer.fit_transform(XD_train) #train and transform the train data 

<319x292 sparse matrix of type '<class 'numpy.float64'>'
	with 638 stored elements in Compressed Sparse Row format>

In [45]:
Xtrain_features = Dict_vectorizer.transform(XD_train)#transform the train data
Xtest_features = Dict_vectorizer.transform(XD_test)#transform the test data

In [46]:
#define classifers
mnb2 = MultinomialNB() 
svm2 = SGDClassifier(loss='hinge', max_iter=100)

In [47]:
#train the multinomial naive bayes classfier
mnb2.fit(Xtrain_features,YD_train)

MultinomialNB()

In [48]:
#predict the multinomial naive bayes classfier
mnb2_predictions = mnb2.predict(Xtest_features)

In [49]:
#call the get metrics function to get the evaluation metrics
get_metrics(true_labels=YD_test,predicted_labels=mnb2_predictions)

Accuracy: 0.97
Precision: 0.97
Recall: 0.97
F1 Score: 0.97


In [50]:
#call the inbuild confusion matrix to get the confusion matrix
confusion_matrix(YD_test,mnb2_predictions)

array([[60,  4],
       [ 0, 74]], dtype=int64)

In [51]:
#train the multinomial svm classfier
svm2.fit(Xtrain_features,YD_train)

SGDClassifier(max_iter=100)

In [52]:
svm2_predictions = svm2.predict(Xtest_features) #predict
get_metrics(true_labels=YD_test,predicted_labels=svm2_predictions) # get the evaluation metrics

Accuracy: 0.96
Precision: 0.97
Recall: 0.96
F1 Score: 0.96


In [53]:
confusion_matrix(YD_test,svm2_predictions) # get confusion metrics

array([[59,  5],
       [ 0, 74]], dtype=int64)

From the above two classifiers, naive bayes has performed better than svm classifer

##### output the names together with their predicted and actual genders for the errors of your best classifier

In [54]:
df = data.iloc[YD_test.index.tolist()] #slice the original dataframe to create dataframe of the test data

In [55]:
df['predicted_label'] = mnb2_predictions.tolist() #add a column of predicted values of naive bayes

C:\Users\thanu\anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [56]:
#add a column of the actual labels with 'male' and 'female',  for the iterate the values of the labels and append a label
#from male or female to the created kist by comparing whether it is 1 or 0
list1 = []
for i in df['label']:
    if i == 1:
        list1.append('male')
    else :
        list1.append('female')
df.loc[:,'actual label'] = list1

C:\Users\thanu\anaconda3\envs\py37\lib\site-packages\pandas\core\indexing.py:1597: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value
C:\Users\thanu\anaconda3\envs\py37\lib\site-packages\pandas\core\indexing.py:1676: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)


In [57]:
#add a column of the predicted labels with 'male' and 'female',  for the iterate the values of the labels and append a label
#from male or female to the created kist by comparing whether it is 1 or 0
list2 = []
for i in df['predicted_label']:
    if i == 1:
        list2.append('male')
    else :
        list2.append('female')
df.loc[:,'predicted label'] = list2

In [58]:
df.drop(['label','predicted_label'], axis=1) #remove the label and predicted label column with 1s and 0s

names actual label predicted label
13        ධනපාල         male            male
267        සනුක         male            male
106      මධුසංඛ         male            male
47   ක්‍රිස්ටෝප         male            male
74     විරාජිනී       female          female
..          ...          ...             ...
128      යුරේෂ්         male            male
444       අංජලී       female          female
337       විදුර         male            male
327     දමයන්ති       female          female
256       හර්ෂි       female          female

[138 rows x 3 columns]

In [64]:
for index, row in df.iterrows():
    if row['actual label'] != row['predicted label']:
        print({'names':row['names'],'actual label': row['actual label'],'predicted label':row['predicted label']})

{'names': 'මාලතී', 'actual label': 'female', 'predicted label': 'male'}
{'names': 'නේරංජා', 'actual label': 'female', 'predicted label': 'male'}
{'names': 'කුසුම්', 'actual label': 'female', 'predicted label': 'male'}
{'names': 'ගයංගා', 'actual label': 'female', 'predicted label': 'male'}


In [59]:
#define a function to get the most siginificant features to classify the names
def significant_features(vectorizer,classifier,n=20):
    class_labels = classifier.classes_ #get the class labels passsed to the classifer
    feature_names =vectorizer.get_feature_names() #get the features names from the vectorizer
    topn_female = sorted(zip(classifier.feature_count_[0], 
    feature_names),reverse=True)[:n] #pair the features count of female label[0] with feature names and sort those in descending order
    listfemale = [] #create a list to get the important features to identify female names
    for i in topn_female:
        listfemale.append(i[1])
    topn_male = sorted(zip(classifier.feature_count_[1], 
    feature_names),reverse=True)[:n]#pair the features count of male label[0] with feature names and sort those in descending order
    listmale=[]#create a list to get the important features to identify male names
    for i in topn_male:
        listmale.append(i[1])
    print("significant features of males : {} ".format(listmale))
    print()
    print("significant features of females : {} ".format(listfemale))

In [60]:
significant_features(Dict_vectorizer,mnb2)

significant features of males : ['last_letter=න්', 'last_letter=ත්', 'last_letter=ත', 'last_letter=ක', 'last_letter=ර', 'last2_letters=න්ත', 'last_letter=ල්', 'last_letter=ද', 'last2_letters=න්ද', 'last_letter=ඳු', 'last_letter=ග', 'last_letter=රි', 'last_letter=න', 'last2_letters=ෂාන්', 'last_letter=ලි', 'last_letter=ල', 'last_letter=ය', 'last2_letters=සිරි', 'last2_letters=රංග', 'last_letter=ව'] 

significant features of females : ['last_letter=කා', 'last_letter=නි', 'last_letter=ලා', 'last_letter=ෂා', 'last_letter=නී', 'last_letter=තා', 'last_letter=ණි', 'last_letter=රි', 'last_letter=රා', 'last_letter=මි', 'last_letter=නා', 'last_letter=දි', 'last_letter=ති', 'last2_letters=න්ති', 'last_letter=යා', 'last_letter=ණී', 'last2_letters=ෂිකා', 'last2_letters=ෂානි', 'last_letter=ලි', 'last_letter=රී'] 
